name: Check Nexus Credentials

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'alandtse'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup UNEX
        uses: alandtse/nexus-workflows/.github/actions/setup-unex@main

      - name: Check Nexus Credentials
        uses: alandtse/nexus-workflows/.github/actions/check-nexus@main
        with:
          nexus-session-cookie: ${{ secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
          nexus-api-key: ${{ secrets.UNEX_APIKEY }}
