name: "Check Nexus credentials"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'alandtse'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
          include-prerelease: false
      - name: Download NexusUploader
        run: dotnet tool install -g BUTR.NexusUploader
      - name: Check Nexus Cookies
        # https://github.com/agc93/nexus-uploader using fork https://github.com/BUTR/BUTR.NexusUploader
        env:
          UNEX_SESSION_COOKIE: ${{ secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
          UNEX_APIKEY: ${{ secrets.UNEX_APIKEY }}
        run: |
          unex check --session-cookie $UNEX_SESSION_COOKIE
      - name: Check Nexus API Key
        # https://github.com/agc93/nexus-uploader
        # https://www.nexusmods.com/users/myaccount?tab=api%20access
        env:
          UNEX_SESSION_COOKIE: ${{ secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
          UNEX_APIKEY: ${{ secrets.UNEX_APIKEY }}
        run: |
          unex check --key $UNEX_APIKEY
